# Generated by Django 2.1.11 on 2019-10-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvelApp', '0002_auto_20191003_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favorite_character',
        ),
    ]
