# Generated by Django 2.1.11 on 2019-10-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelApp', '0003_remove_movie_favorite_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
