# Generated by Django 2.1.11 on 2019-10-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelApp', '0004_auto_20191004_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField()),
            ],
        ),
    ]
