# Generated by Django 2.1.11 on 2019-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelApp', '0005_comic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ability', models.PositiveSmallIntegerField()),
                ('affiliation', models.CharField(max_length=10)),
                ('reason', models.TextField()),
            ],
        ),
    ]
