# Generated by Django 2.1.11 on 2019-10-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelApp', '0006_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('future_release', models.DateField()),
                ('related_movie', models.CharField(max_length=50)),
                ('plot', models.TextField()),
            ],
        ),
    ]
