# Generated by Django 2.1.11 on 2019-10-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvelApp', '0007_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='ability',
        ),
    ]
