# Generated by Django 2.1.11 on 2019-10-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marvelApp', '0011_movie_comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='suggestion',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='marvelApp.Suggestion'),
        ),
    ]
