# Generated by Django 2.1.11 on 2019-10-09 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marvelApp', '0013_auto_20191009_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='character',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='suggestion',
        ),
        migrations.AddField(
            model_name='movie',
            name='characters',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='character', to='marvelApp.Character'),
        ),
        migrations.AddField(
            model_name='movie',
            name='comics',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='comic', to='marvelApp.Comic'),
        ),
        migrations.AddField(
            model_name='movie',
            name='suggestions',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggestion', to='marvelApp.Suggestion'),
        ),
    ]
