# Generated by Django 2.1.11 on 2019-10-09 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marvelApp', '0014_auto_20191009_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='characters',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='marvelApp.Character'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comics',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='comics', to='marvelApp.Comic'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='suggestions',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='marvelApp.Suggestion'),
        ),
    ]
