# Generated by Django 2.1.11 on 2019-10-09 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marvelApp', '0016_auto_20191009_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='comics',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='character',
            name='movie',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='marvelApp.Movie'),
        ),
        migrations.AddField(
            model_name='comic',
            name='movie',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='marvelApp.Movie'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='movie',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='marvelApp.Movie'),
        ),
    ]
